// Code generated by protoc-gen-go.
// source: instance.proto
// DO NOT EDIT!

/*
Package collection is a generated protocol buffer package.

It is generated from these files:
	instance.proto

It has these top-level messages:
	SerialPathNode
	SerialResource
	SerialInstance
*/
package collection

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type SerialPathNode struct {
	Name     []byte `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	ParentID []byte `protobuf:"bytes,2,opt,name=ParentID,proto3" json:"ParentID,omitempty"`
}

func (m *SerialPathNode) Reset()         { *m = SerialPathNode{} }
func (m *SerialPathNode) String() string { return proto.CompactTextString(m) }
func (*SerialPathNode) ProtoMessage()    {}

type SerialResource struct {
	ID        []byte            `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Hash      []byte            `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
	PathNodes []*SerialPathNode `protobuf:"bytes,3,rep,name=PathNodes" json:"PathNodes,omitempty"`
}

func (m *SerialResource) Reset()         { *m = SerialResource{} }
func (m *SerialResource) String() string { return proto.CompactTextString(m) }
func (*SerialResource) ProtoMessage()    {}

func (m *SerialResource) GetPathNodes() []*SerialPathNode {
	if m != nil {
		return m.PathNodes
	}
	return nil
}

type SerialInstance struct {
	CollectionId []byte            `protobuf:"bytes,1,opt,name=CollectionId,proto3" json:"CollectionId,omitempty"`
	Resources    []*SerialResource `protobuf:"bytes,2,rep,name=Resources" json:"Resources,omitempty"`
	Directories  []*SerialResource `protobuf:"bytes,3,rep,name=Directories" json:"Directories,omitempty"`
}

func (m *SerialInstance) Reset()         { *m = SerialInstance{} }
func (m *SerialInstance) String() string { return proto.CompactTextString(m) }
func (*SerialInstance) ProtoMessage()    {}

func (m *SerialInstance) GetResources() []*SerialResource {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *SerialInstance) GetDirectories() []*SerialResource {
	if m != nil {
		return m.Directories
	}
	return nil
}
